### PR TITLE
Fixes for Windows

### LINKED ISSUE #33: Can't compile on windows
Windows 7 Pro, 64 bit.  mingw-w64.  go 1.5.

Compilation fails with error "can't convert -1 to mdb_filehandle_t".

This appears to be caused by an assumption that the mdb_filehandle_t will be an int, which is not the case on Windows.

```
func (env *Env) FD() (uintptr, error) {
	var mf C.mdb_filehandle_t
	ret := C.mdb_env_get_fd(env._env, &mf)
	err := operrno("mdb_env_get_fd", ret)
	if err != nil {
		return 0, err
	}
	if mf == C.mdb_filehandle_t(-1) { <<< error. assumes POSIX file handle.
		return 0, errNotOpen
	}
	return uintptr(mf), nil
}
```

```
/** An abstraction for a file handle.
 *	On POSIX systems file handles are small integers. On Windows
 *	they're opaque pointers.
 */
#ifdef _WIN32
typedef	void *mdb_filehandle_t;
#else
typedef int mdb_filehandle_t;
#endif
```

### PR DESCRIPTION
**Pull request by bmatsuo**
Fixes #33 

This branch contains several modifications to get the lmdb package building, with all tests passing, on Windows.

- Usage of `ioutil.TempDir` was made portable by allowing the package to use the os-dependent default temporary directory instead of "/tmp".
 
- Translate LMDB return values to the proper syscall.Errno constant values in the internal `operrno` function. This allows error handling code to be portable as long as named errno constants are used instead of numeric errno literals.

### CODE REVIEW

File: lmdb/env.go [hunk 1]
```diff
@@ -103,7 +103,7 @@ func (env *Env) FD() (uintptr, error) {
 	if err != nil {
 		return 0, err
 	}
-	if mf == C.mdb_filehandle_t(-1) {
+	if uintptr(mf) == ^uintptr(0) {
```
Comment (bmatsuo) [inline lmdb/env.go]: The RHS probably deserves a locally scoped named constant with a comment about its value.

File: lmdb/error_windows.go [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+	case 12:
+		errno = syscall.ENOMEM /* 12, INVALID_ACCESS */
+	case 13:
+		errno = syscall.EACCES /* 13, INVALID_DATA */
+	case 16:
+		errno = syscall.EBUSY /* 16, CURRENT_DIRECTORY */
+	case 22:
+		errno = syscall.EINVAL /* 22, BAD_COMMAND */
+	case 28:
+		errno = syscall.ENOSPC /* 28, OUT_OF_PAPER */
```
Comment (bmatsuo) [inline lmdb/error_windows.go]: I need to look into a way to stop using numeric literals.

**Comment by bmatsuo** [comment]
There also needs to be some extra error handling documentation for Windows.

File: lmdb/env.go [hunk 3]
```diff
@@ -97,16 +97,23 @@ var errNotOpen = fmt.Errorf("enivornment is not open")
 //
 // See mdb_env_get_fd.
 func (env *Env) FD() (uintptr, error) {
-	var mf C.mdb_filehandle_t
-	ret := C.mdb_env_get_fd(env._env, &mf)
+	// fdInvalid is the value -1 as a uintptr, which is used by LMDB in the
+	// case that env has not been opened yet.  the strange construction is done
+	// to avoid constant value overflow errors at compile time.
```
Comment (bmatsuo) [inline lmdb/env.go]: grammar

File: lmdb/error.go [hunk 4]
```diff
@@ -58,7 +58,9 @@ const (
 
 // Errno is an error type that represents the (unique) errno values defined by
 // LMDB.  Other errno values (such as EINVAL) are represented with type
-// syscall.Errno.
+// syscall.Errno.  On Windows, LMDB return codes are translated in to the set
```
Comment (bmatsuo) [inline lmdb/error.go]: into*

File: lmdb/error.go [hunk 5]
```diff
@@ -58,7 +58,9 @@ const (
...
+// of portable Unix syscall.Errno constants (e.g. syscall.EINVAL,
```
Comment (bmatsuo) [inline lmdb/error.go]: ~~of~~

File: lmdb/error_windows.go [hunk 6]
```diff
@@ -0,0 +1,43 @@
+package lmdb
+
+/*
+#include "errno.h"
```
Comment (bmatsuo) [inline lmdb/error_windows.go]:
```
#include <errno.h>
```
